name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon check --deny-warn
      - run: moon test
      - run: moon fmt --check
